require "json"

package = JSON.parse(File.read(File.join(__dir__, "package.json")))

Pod::Spec.new do |s|
  s.name         = "NitroMLKitFaceRecognition"
  # Must match nitro.json's `ios.iosModuleName` — Nitrogen's generated bridge
  # files import "NitroMLKitRecognition-Swift.h", so the compiled Swift module
  # has to be NitroMLKitRecognition even though the pod is named
  # NitroMLKitFaceRecognition (the podspec filename must match `s.name`).
  s.module_name  = "NitroMLKitRecognition"
  s.version      = package["version"]
  s.summary      = package["description"]
  s.homepage     = package["repository"]["url"]
  s.license      = package["license"]
  s.authors      = package["author"]
  s.source       = { :git => "https://github.com/pologonzalo/react-native-nitro-mlkit.git", :tag => s.version }

  # ML Kit 7 is 15.5+; the Swift impl needs nothing newer.
  s.platforms    = { :ios => "15.5" }

  s.source_files = [
    "ios/**/*.{swift,h,m,mm,cpp}"
  ]

  s.dependency "GoogleMLKit/FaceDetection", "~> 7.0"
  # TensorFlowLite**Swift**, not TensorFlowLiteObjC: the ObjC pod ships no
  # module map, so `import` fails and `pod install` broke — that is why this
  # package shipped Android-only in 0.1.0-beta.0. This one vends the
  # `TensorFlowLite` Swift module.
  s.dependency "TensorFlowLiteSwift", "~> 2.14"

  s.pod_target_xcconfig = {
    "SWIFT_VERSION" => "5.9"
  }

  # Add all files generated by Nitrogen
  load 'nitrogen/generated/ios/NitroMLKitRecognition+autolinking.rb'
  add_nitrogen_files(s)
end
